YANG/ccamp/otn-tunnel/ietf-otn-tunnel.tree, YANG/ccamp/otn-tunnel/ietf-otn-tunnel.yang
Alignment with the latest version of the TE Tunnel model (draft-ietf-teas-yang-te-15)
=> 2018-06-14 Alignment with TE Tunnel

YANG/ccamp/otn-tunnel/ietf-otn-tunnel.yang
This version address the open issue #6  and #7 , with a few other adjustment. 
Request for review and the draft -03 is expected to be submitted by July 2nd.
=> Haomian otn tunnel patch 3

YANG/ccamp/otn-tunnel/ietf-otn-types.yang
Update OTN Type identity list. Only add more comments/issues for discussion.
=> otn-types in draft-ietf-ccamp-otn-tunnel-model-03

YANG/ccamp/otn-tunnel/ietf-otn-types.yang
Several descriptions are added to fix the errors in YANG validation. Upload as demand in ietf-otn-topology.
=> Upload to fix issue in otn-types, in -04

YANG/ccamp/Client-signal-yang/ietf-eth-tran-service.yang, YANG/ccamp/Client-signal-yang/ietf-eth-tran-types.yang, YANG/ccamp/Client-signal-yang/ietf-trans-client-service.yang
for draft-zheng-ccamp-client-signal-yang-07. 
- Solving the issue from Tom Petch on the list about -06; 
- Addressing the issue about 'transport', replaced by 'transport network'.
=> to commit -07

YANG/ccamp/layer1-types/ietf-layer1-types.yang, YANG/ccamp/otn-topology/ietf-otn-topology.tree, YANG/ccamp/otn-topology/ietf-otn-topology.yang, YANG/ccamp/otn-tunnel/ietf-otn-tunnel.tree, YANG/ccamp/otn-tunnel/ietf-otn-tunnel.yang
Partially solve some problems in YANG doctor Review. 
See https://mailarchive.ietf.org/arch/msg/ccamp/XOXNzCrJV5M_XNpCEvpGWGjuLqc for all the comments.
=> YANG Doctor: 1st update

YANG/ccamp/client-pm/ietf-eth-service-pm.tree, YANG/ccamp/client-pm/ietf-eth-service-pm.yang
Reverts haomianzheng/IETF-ACTN-YANG-Model#59 to address yang validation...
=> Revert "PM model for ccamp-interim"

YANG/ccamp/otn-topology/ietf-otn-topology.yang, YANG/ccamp/otn-tunnel/ietf-otn-tunnel.tree, YANG/ccamp/otn-tunnel/ietf-otn-tunnel.yang, YANG/ccamp/otn-tunnel/ietf-te-types@2019-02-06.yang, YANG/ccamp/otn-tunnel/ietf-te@2019-02-15.tree, YANG/ccamp/otn-tunnel/ietf-te@2019-02-15.yang
Addressing some YANG doctor review comments:
- fix otn-tunnel compilation errors
- removing the two groupings in otn-topology
Other comments still to be addressed
Co-authored-by: haomianzheng <zhenghaomian@huawei.com>
Co-authored by: agva123 <agva123@gmail.com>
=> Yang doctor

YANG/ccamp/l1csm/ietf-l1csm.tree, YANG/ccamp/l1csm/ietf-l1csm.yang, YANG/ccamp/layer1-types/ietf-layer1-types.yang, YANG/ccamp/otn-topology/ietf-otn-topology.tree
Proposed resolution for the L1CSM YANG model review comments (#64)
=> Proposed resolution for the L1CSM YANG model review comments

YANG/ccamp/otn-topology/ietf-otn-topology.yang, YANG/ccamp/otn-tunnel/ietf-otn-tunnel.tree, YANG/ccamp/otn-tunnel/ietf-otn-tunnel.yang, YANG/ccamp/otn-tunnel/ietf-te-types@2019-02-06.yang, YANG/ccamp/otn-tunnel/ietf-te@2019-02-15.tree, YANG/ccamp/otn-tunnel/ietf-te@2019-02-15.yang
Addressing some YANG doctor review comments:
- https://mailarchive.ietf.org/arch/msg/ccamp/CqHx1813l9OfKkA_6ijZ5E_zlvs/
- https://mailarchive.ietf.org/arch/msg/ccamp/hevNlzTnh9ra4Ru0q2VwmFmMwU4/
Comments addressed:
- fix otn-tunnel compilation errors
- removing the two groupings in otn-topology
The comments on the prefixes is pending resolution of mailing list discussions.
Other comments are on the draft and outside the scope of this PR.
Co-authored-by: haomianzheng <zhenghaomian@huawei.com>
Co-authored-by agva123 <agva123@gmail.com>
=> Addressing Yang doctor review comments

YANG/ccamp/l1csm/ietf-l1csm.yang
Solve https://github.com/haomianzheng/IETF-ACTN-YANG-Model/issues/78
=> Update ietf-l1csm.yang per Tom's comments

YANG/ccamp/otn-tunnel/ietf-otn-tunnel.yang, YANG/ccamp/otn-tunnel/ietf-te@2019-02-15.yang
Check how to fix IETF YANG validation errors
=> Fixing IETF validation errors with ietf-otn-tunnel

YANG/ccamp/otn-topology/ietf-otn-topology.tree, YANG/ccamp/otn-topology/ietf-otn-topology.yang
Aligned OTN topology with the new prefix (otnt)
=> OTN topology prefix

YANG/ccamp/Client-signal-yang/ietf-eth-tran-types.yang, YANG/ccamp/client-pm/ietf-service-pm.yang
Prepare for IETF 111, changing eth-tran-types to support E-Tree.
=> Change client-signal models and PM model

YANG/ccamp/layer1-types/ietf-layer1-types.yang, YANG/ccamp/otn-topology/ietf-otn-topology.tree, YANG/ccamp/otn-topology/ietf-otn-topology.yang
Prepare layer1-types and otn-topology YANG models for WG LC
Fix #97, fix #100; fix #101; fix #102 and fix #103
=> Prepare for OTN topology WG LC

YANG/ccamp/l1csm/ietf-l1csm.tree, YANG/ccamp/l1csm/ietf-l1csm.yang
Update L1CSM YANG model:
- Removed performance metrics: see #115
=> L1CSM WG LC Preparation

YANG/ccamp/l1csm/ietf-l1csm.tree, YANG/ccamp/l1csm/ietf-l1csm.yang
=> Define the endpoints as a list

YANG/ccamp/otn-tunnel/ietf-otn-tunnel.tree, YANG/ccamp/otn-tunnel/ietf-otn-tunnel.yang
Updated Victor mail address: fix #107
Recompiled with the latest version of layer1-types
=> Updated Victor mail address

YANG/ccamp/layer1-types/ietf-layer1-types.tree, YANG/ccamp/layer1-types/ietf-layer1-types.yang, YANG/ccamp/otn-topology/ietf-otn-topology-full.tree, YANG/ccamp/otn-topology/ietf-otn-topology.tree, YANG/ccamp/otn-topology/ietf-otn-topology.yang, YANG/ccamp/otn-tunnel/ietf-otn-tunnel.tree
Minor editorial updates to align with https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang/files/10510430/new-ml-topology-models-00.txt: see #139
=> Few minor editorial updates to OTN Topology YANG model

.gitignore, YANG/ccamp/layer1-types/ietf-layer1-types.tree, YANG/ccamp/layer1-types/ietf-layer1-types.yang, YANG/ccamp/layer1-types/odu-label-restrictions-examples.json, YANG/ccamp/layer1-types/odu-label-restrictions-examples.txt
Updated YANG model
Updated JSON examples
=> Addressing IESG comments to L1 Types
